# Generated by Django 5.2.4 on 2025-08-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="department",
            field=models.CharField(
                choices=[
                    ("CSE", "Computer Science"),
                    ("ECE", "Electronics"),
                    ("ME", "Mechanical"),
                    ("CE", "Civil"),
                    ("EEE", "Electrical"),
                ],
                default="computer",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="year",
            field=models.CharField(
                choices=[
                    ("1", "First Year"),
                    ("2", "Second Year"),
                    ("3", "Third Year"),
                    ("4", "Fourth Year"),
                ],
                default=1,
                max_length=10,
            ),
        ),
    ]
