# Generated by Django 5.2.4 on 2025-08-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0002_uploadedfile_department_uploadedfile_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="department",
            field=models.CharField(
                choices=[
                    ("Computer Science", "Computer Science"),
                    ("Electronics", "Electronics"),
                    ("Mechanical", "Mechanical"),
                    ("Civil", "Civil"),
                    ("Electrical", "Electrical"),
                ],
                default="computer",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="year",
            field=models.CharField(
                choices=[
                    ("First Year", "First Year"),
                    ("Second Year", "Second Year"),
                    ("Third Year", "Third Year"),
                    ("Fourth Year", "Fourth Year"),
                ],
                default=1,
                max_length=25,
            ),
        ),
    ]
