# Generated by Django 5.2.4 on 2025-08-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0003_alter_uploadedfile_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="department",
            field=models.CharField(
                choices=[
                    ("Computer Science", "Computer Science"),
                    ("Electronics", "Electronics"),
                    ("Mechanical", "Mechanical"),
                    ("Civil", "Civil"),
                    ("Electrical", "Electrical"),
                    ("Data Science", "Data Science"),
                ],
                default="computer",
                max_length=25,
            ),
        ),
    ]
