# Generated by Django 5.2.4 on 2025-08-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0005_alter_uploadedfile_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to="protected/"),
        ),
    ]
